# Generated by Django 4.0.5 on 2023-03-08 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_answer_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='info',
        ),
    ]
