# Generated by Django 4.0.5 on 2023-03-10 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_answer_downvoted_answer_downvoteds_by_answer_upvoted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='downvoted',
            new_name='downvotes',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='downvoteds_by',
            new_name='downvotes_by',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='upvoted',
            new_name='upvotes',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='upvoteds_by',
            new_name='upvotes_by',
        ),
    ]
