# Generated by Django 4.0.5 on 2023-03-18 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_rename_downvoted_answer_downvotes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
