# Generated by Django 4.0.5 on 2023-03-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_qcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-02-02'),
            preserve_default=False,
        ),
    ]
