# Generated by Django 4.0.5 on 2023-03-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_qcomment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, upload_to='question_images'),
        ),
    ]
